name: Release
on:
  push:
    tags:
      - 'v*'
jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.19' # The Go version to download (if necessary) and use.
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Update Version (ProductVersion)
        uses: deef0000dragon1/json-edit-action/@v1
        env:
          FILE: cmd/arcdps-log-uploader/_res/versioninfo.json
          KEY: StringFileInfo.ProductVersion
          VALUE: ${{ steps.get_version.outputs.VERSION }}
      - name: Update Version (FileVersion)
        uses: deef0000dragon1/json-edit-action/@v1
        env:
          FILE: cmd/arcdps-log-uploader/_res/versioninfo.json
          KEY: StringFileInfo.FileVersion
          VALUE: ${{ steps.get_version.outputs.VERSION }}

      - run: make build_i386
      - run: make build_amd64

      - name: "Zip Artifacts"
        run: find ./out -name '*_*.exe' -exec zip -j -D '{}.zip' '{}' \;
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@main
        with:
          commitMode: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "./out/*_*.exe.zip"
          allowUpdates: true
          body: ${{steps.github_release.outputs.changelog}}
          prerelease : true
