on: push
name: Build Application
jobs:
  checks:
    name: run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: run
        uses: cedrickring/golang-action/go.1.14@1.6.0
        env:
          GO111MODULE: "on"
        with:
          args: make build
